version: "3.2"
services:



  adminer:
    image: adminer
    network_mode: host
    # networks:
    #   - frontend
    #   - backend
    ports:
      - 8080:8080    
  db:
    image: mysql:${MYSQL_VERSION:-latest}
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/sql/:/docker-entrypoint-initdb.d/
    network_mode: host
    # networks:
    #   - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    container_name: mysql
networks:
  frontend:
  backend: